name: 'prettiefy'
on: push

jobs:
  prettier: # Automatically runs prettier on all your changes
    runs-on: ubuntu-latest
    steps:
      - name: Prettier Action
        uses: creyD/prettier_action@v3.1
        with: # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,ts}
          only_changed: True
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
