name: Stylefy

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  style-fix:
    # Name the Job
    name: Run prettier for the code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - env: 
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
      - uses: actions/checkout@v2
      # Add NodeJS v12
      - name: Uses NodeJS v12
      - uses: actions/setup-node@v1
        with: 
          node-version: '12'
      # Install Prettier
      - name: Install Prettier
      - run: npm install -y -g prettier
      # Install project dependencies
      - name: Install project dependencies
      - run: npm install -y
      # Run style:check
      - name: Run style:check
      - run: npm run style:check
